name: Test echo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo Result
      run: echo ${{github.workflow}} is ${{job.status}}
    - name: Webhook
      if: ${{ always() }}
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{"content": "@everyone ${{github.workflow}} is ${{job.status}}", "allowed_mentions": {"parse": ["everyone"]}}'
